/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecommandationsRouteImport } from './routes/recommandations'
import { Route as RecompensesRouteImport } from './routes/recompenses'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommandationsRoute = RecommandationsRouteImport.update({
  id: '/recommandations',
  path: '/recommandations',
  getParentRoute: () => rootRouteImport,
} as any)
const RecompensesRoute = RecompensesRouteImport.update({
  id: '/recompenses',
  path: '/recompenses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recommandations': typeof RecommandationsRoute
  '/recompenses': typeof RecompensesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recommandations': typeof RecommandationsRoute
  '/recompenses': typeof RecompensesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recommandations': typeof RecommandationsRoute
  '/recompenses': typeof RecompensesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/recommandations' | '/recompenses'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recommandations' | '/recompenses'
  id: '__root__' | '/' | '/recommandations' | '/recompenses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecommandationsRoute: typeof RecommandationsRoute
  RecompensesRoute: typeof RecompensesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommandations': {
      id: '/recommandations'
      path: '/recommandations'
      fullPath: '/recommandations'
      preLoaderRoute: typeof RecommandationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recompenses': {
      id: '/recompenses'
      path: '/recompenses'
      fullPath: '/recompenses'
      preLoaderRoute: typeof RecompensesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecommandationsRoute: RecommandationsRoute,
  RecompensesRoute: RecompensesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
